### ISSUE TITLE
Add Password Protection to the files 

### ISSUE THREAD

**Issue by iamakhileshmishra** [PCON-Hacktoberfest-2022/YourSpace#2]
Add a feature so that only the person with the password will be able to view the files if the link is shared with them.

**Comment by mohitkumaragrawal** [comment]
I can do it, please assign this to me

**Comment by iamakhileshmishra** [comment]
Ok assigning this to you go ahead..

**Comment by iamakhileshmishra** [comment]
Review the PR for the download button and Raise it again.
Don't forget to take a fresh pull before working.

**Comment by mohitkumaragrawal** [comment]
This issue should be closed now
