### ISSUE TITLE
Add a features so that all the Blog get deleted after 24 hrs.

### ISSUE THREAD

**Issue by iamakhileshmishra** [PCON-Hacktoberfest-2022/YourSpace#3]
I want the contributor to add a feature so that the File created by the author gets deleted after 24hrs of upload time.

**Comment by Kunalpal215** [comment]
I will use node-cron npm package whose instance will automatically delete files created by users of the app after 24 hrs. Can you assign it to me ?

**Comment by iamakhileshmishra** [comment]
Have you gone through the code and hosted website..?

**Comment by Kunalpal215** [comment]
Yes... I have gone through the code and hosted website

**Comment by iamakhileshmishra** [comment]
Ok assigning this to you go ahead

**Comment by Kunalpal215** [comment]
I have created pull request
